stages:
  - build
  - test

build-layer:
  stage: build
  tags: ["arch:amd64"]
  image: registry.ddbuild.io/images/docker:20.10
  parallel:
    matrix:
      - NODE_VERSION: [ "14.15", "16.14", "18.12", "20.9" ]
  artifacts:
    expire_in: 10 min # temp value
    paths:
      - .layers/*.zip
  variables:
    CI_ENABLE_CONTAINER_IMAGE_BUILDS: "true" # Enable docker in CI runner
  script:
    - ./scripts/build_layers.sh

check-size:
  stage: test
  tags: ["arch:amd64"]
  image: registry.ddbuild.io/images/docker:20.10
  needs: 
    - build-layer
  dependencies:
    - build-layer
  parallel:
    matrix:
      - NODE_VERSION: [ "14.15", "16.14", "18.12", "20.9" ]
  script: ./scripts/check_size.sh
