stages:
  - build

variables:
  INTERNAL_REGISTRY: 486234852809.dkr.ecr.us-east-1.amazonaws.com

build-layer:
  stage: build
  tags: ["runner:docker"]
  image: $INTERNAL_REGISTRY/docker:20.10
  parallel:
    matrix:
      - NODE_VERSION: [ "14.15", "16.14", "18.12", "20.9" ]
  artifacts:
    expire_in: 10 min # temp value
    paths:
      - .layers/*.zip
  variables:
    CI_ENABLE_CONTAINER_IMAGE_BUILDS: "true" # Enable docker in CI runner
  script:
    - ./scripts/build_layers.sh
