name: update-deps

on:
  schedule:
    - cron: "0 10 * * *" # Run at 10 am every day
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    environment:
      name: protected-main-env
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: "20.x"

      - name: Update Dependencies
        run: |
          yarn install
          yarn upgrade

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@18f7dc018cc2cd597073088f7c7591b9d1c02672 # v3.14.0
        with:
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: update dependencies
          title: Update Dependencies
          body: |
            Autogenerated PR to update all deps to latest versions
          branch: update-dependencies
